//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36468
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report_pack_generator.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class excel_settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static excel_settings defaultInstance = ((excel_settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new excel_settings())));
        
        public static excel_settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public string pipline_warp_column {
            get {
                return ((string)(this["pipline_warp_column"]));
            }
            set {
                this["pipline_warp_column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R")]
        public string borderux_column {
            get {
                return ((string)(this["borderux_column"]));
            }
            set {
                this["borderux_column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool trim_3_page {
            get {
                return ((bool)(this["trim_3_page"]));
            }
            set {
                this["trim_3_page"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool wrap_text {
            get {
                return ((bool)(this["wrap_text"]));
            }
            set {
                this["wrap_text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool generate_pdf {
            get {
                return ((bool)(this["generate_pdf"]));
            }
            set {
                this["generate_pdf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool unhide_column {
            get {
                return ((bool)(this["unhide_column"]));
            }
            set {
                this["unhide_column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool new_renew_column {
            get {
                return ((bool)(this["new_renew_column"]));
            }
            set {
                this["new_renew_column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool trim_2_page {
            get {
                return ((bool)(this["trim_2_page"]));
            }
            set {
                this["trim_2_page"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool trim_additionbrdx {
            get {
                return ((bool)(this["trim_additionbrdx"]));
            }
            set {
                this["trim_additionbrdx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rm_CRM {
            get {
                return ((bool)(this["rm_CRM"]));
            }
            set {
                this["rm_CRM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rm_Verbatim {
            get {
                return ((bool)(this["rm_Verbatim"]));
            }
            set {
                this["rm_Verbatim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rm_Brokerdecision {
            get {
                return ((bool)(this["rm_Brokerdecision"]));
            }
            set {
                this["rm_Brokerdecision"] = value;
            }
        }
    }
}
