//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36468
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report_pack_generator.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class folder : global::System.Configuration.ApplicationSettingsBase {
        
        private static folder defaultInstance = ((folder)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new folder())));
        
        public static folder Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Cover for Client</string>
  <string>Commentaries</string>
  <string>Pipeline</string>
  <string>Analysis</string>
  <string>Bordereaux</string>
  <string>Additional Requirements</string>
  <string>Data Sources and Service Summary</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection folders {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["folders"]));
            }
            set {
                this["folders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool covert_pdf {
            get {
                return ((bool)(this["covert_pdf"]));
            }
            set {
                this["covert_pdf"] = value;
            }
        }
    }
}
