//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36468
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report_pack_generator.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class report_pack : global::System.Configuration.ApplicationSettingsBase {
        
        private static report_pack defaultInstance = ((report_pack)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new report_pack())));
        
        public static report_pack Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string output_path {
            get {
                return ((string)(this["output_path"]));
            }
            set {
                this["output_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\inmum-i-fs5\\group$\\Global Corporate & Data Strategy\\FMS\\Process\\BIA\\FINMAR\\Comm" +
            "entaries\\")]
        public string commentary_path {
            get {
                return ((string)(this["commentary_path"]));
            }
            set {
                this["commentary_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\gbips-i-fs101\\group\\FINMAR Market Services\\Client Service\\Reports\\Generated Rep" +
            "orts")]
        public string generated_path {
            get {
                return ((string)(this["generated_path"]));
            }
            set {
                this["generated_path"] = value;
            }
        }
    }
}
